services:
  mysql:
    image: mysql:8.0
    container_name: tms_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tms_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tms_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - tms_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  eureka-server:
    build: ./eureka-server
    container_name: tms_eureka
    ports:
      - "8761:8761"
    env_file: .env
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - tms_network

  api-gateway:
    build: ./api-gateway
    container_name: tms_gateway
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - eureka-server
    networks:
      - tms_network

  auth-service:
    build: ./auth-service
    container_name: tms_auth
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - tms_network

  timesheet-service:
    build: ./timesheet-service
    container_name: tms_timesheet
    ports:
      - "8082:8082"
    env_file: .env
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - tms_network

  leave-service:
    build: ./leave-service
    container_name: tms_leave
    ports:
      - "8083:8083"
    env_file: .env
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - tms_network

  admin-service:
    build: ./admin-service
    container_name: tms_admin
    ports:
      - "8084:8084"
    env_file: .env
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - tms_network

  zipkin:
    image: openzipkin/zipkin
    container_name: tms_zipkin
    ports:
      - "9411:9411"
    networks:
      - tms_network

  notification-service:
    build: ./notification-service
    container_name: tms_notification
    ports:
      - "8085:8085"
    env_file: .env
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - ZIPKIN_HOST=zipkin
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - tms_network

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  tms_network:
    driver: bridge