server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
         routes:
         - id: auth-service
           uri: lb://auth-service
           predicates:
            - Path=/auth/**

         - id: timesheet-service
           uri: lb://timesheet-service
           predicates:
            - Path=/timesheet/**

         - id: leave-service
           uri: lb://leave-service
           predicates:
             - Path=/leave/**

         - id: admin-service
           uri: lb://admin-service
           predicates:
            - Path=/admin/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
 secret: tms-super-secret-key-must-be-at-least-256-bits-long-for-hmac!!

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: WARN

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
  endpoint:
    health:
      show-details: always