server:
  port: 8084

spring:
  application:
    name: admin-service
  config:
    import: optional:file:../.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/tms_admin_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      exchange: tms.exchange

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.application.adminservice: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  level:
    com.application.adminservice: DEBUG